blank_issues_enabled: false
#contact_links:
#  - name: Bug Reports
#    url: https://kcomain.github.io/bfbVoteCounter/bugreport
#    about: Report bugs here. Big or small, all here.
#  - name: Suggestions
#    url: https://kcomain.github.io/bfbVoteCounter/suggestions
#    about: Please post suggestions here.
#
